export const PRODUCT_CATEGORIES = [
  "Safety Helmets",
  "Safety Boots",
  "Reflective Jackets",
  "Coveralls",
  "Gloves",
  "Respirators",
  "Safety Goggles",
  "Face Shields",
  "Ear Protection",
  "Fall Protection Equipment",
  "Gas Detectors",
  "Fire Extinguishers",
  "First Aid Kits",
  "Spill Response Kits",
  "Traffic Cones",
  "Safety Signage",
  "Lockout/Tagout Devices",
  "Emergency Showers",
  "Eye Wash Stations",
  "Industrial PPE",
  "HSE Training Services",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export type Product = {
  id: string;
  name: string;
  category: ProductCategory;
  supplier: string;
  description: string;
  certifications: string[];
  price: number;
  unit: string;
  availability: "In stock" | "Low stock" | "Made to order";
  rating: number;
  reviews: number;
  delivery: string;
  emoji: string;
};

export const PRODUCTS: Product[] = [
  {
    id: "MP-1001",
    name: "Vented Industrial Safety Helmet",
    category: "Safety Helmets",
    supplier: "Delta Safety Supplies Ltd",
    description: "High-impact ABS shell with 6-point ratchet suspension and chin strap for offshore use.",
    certifications: ["EN 397", "ANSI Z89.1"],
    price: 18500,
    unit: "per unit",
    availability: "In stock",
    rating: 4.7,
    reviews: 214,
    delivery: "2–4 days",
    emoji: "⛑️",
  },
  {
    id: "MP-1002",
    name: "Composite Toe Oil-Resistant Boots",
    category: "Safety Boots",
    supplier: "Niger Delta Industrial Ltd",
    description: "Slip and hydrocarbon-resistant sole, composite toe cap, anti-static and heat resistant to 300°C.",
    certifications: ["EN ISO 20345 S3", "SRC"],
    price: 42900,
    unit: "per pair",
    availability: "In stock",
    rating: 4.6,
    reviews: 168,
    delivery: "3–5 days",
    emoji: "🥾",
  },
  {
    id: "MP-1003",
    name: "Class 3 Reflective Jacket",
    category: "Reflective Jackets",
    supplier: "Delta Safety Supplies Ltd",
    description: "High-visibility yellow jacket with 360° retroreflective banding for night operations.",
    certifications: ["EN ISO 20471 Class 3"],
    price: 12400,
    unit: "per unit",
    availability: "In stock",
    rating: 4.4,
    reviews: 96,
    delivery: "2–3 days",
    emoji: "🦺",
  },
  {
    id: "MP-1004",
    name: "Flame-Resistant Coveralls (Arc-Rated)",
    category: "Coveralls",
    supplier: "Sahara PPE Manufacturing",
    description: "Inherently flame-resistant fabric, 8.9 cal/cm² arc rating, hydrocarbon splash protection.",
    certifications: ["NFPA 2112", "EN ISO 11612"],
    price: 68000,
    unit: "per unit",
    availability: "Low stock",
    rating: 4.8,
    reviews: 132,
    delivery: "5–8 days",
    emoji: "🧑‍🏭",
  },
  {
    id: "MP-1005",
    name: "Cut-Resistant Impact Gloves",
    category: "Gloves",
    supplier: "Sahara PPE Manufacturing",
    description: "Level D cut protection with TPR impact guards and nitrile grip palm for drilling operations.",
    certifications: ["EN 388 4544", "ANSI A4"],
    price: 9800,
    unit: "per pair",
    availability: "In stock",
    rating: 4.5,
    reviews: 187,
    delivery: "2–4 days",
    emoji: "🧤",
  },
  {
    id: "MP-1006",
    name: "Half-Face Respirator with A2P3 Filters",
    category: "Respirators",
    supplier: "Atlantic Detection Systems",
    description: "Silicone facepiece with twin bayonet filters for organic vapour and particulate protection.",
    certifications: ["EN 140", "EN 14387"],
    price: 34500,
    unit: "per kit",
    availability: "In stock",
    rating: 4.6,
    reviews: 74,
    delivery: "4–6 days",
    emoji: "😷",
  },
  {
    id: "MP-1007",
    name: "Anti-Fog Sealed Safety Goggles",
    category: "Safety Goggles",
    supplier: "Delta Safety Supplies Ltd",
    description: "Indirect-vent sealed goggles with permanent anti-fog and anti-scratch coating.",
    certifications: ["EN 166", "ANSI Z87.1"],
    price: 7600,
    unit: "per unit",
    availability: "In stock",
    rating: 4.3,
    reviews: 58,
    delivery: "2–3 days",
    emoji: "🥽",
  },
  {
    id: "MP-1008",
    name: "Helmet-Mounted Face Shield",
    category: "Face Shields",
    supplier: "Delta Safety Supplies Ltd",
    description: "Polycarbonate visor with slot adapter, chemical splash and grinding rated.",
    certifications: ["EN 166 B"],
    price: 15200,
    unit: "per unit",
    availability: "In stock",
    rating: 4.2,
    reviews: 41,
    delivery: "3–5 days",
    emoji: "🛡️",
  },
  {
    id: "MP-1009",
    name: "Electronic Ear Defenders (SNR 31dB)",
    category: "Ear Protection",
    supplier: "Atlantic Detection Systems",
    description: "Level-dependent hearing protection with radio comms for compressor and turbine areas.",
    certifications: ["EN 352-1"],
    price: 58900,
    unit: "per unit",
    availability: "Made to order",
    rating: 4.7,
    reviews: 29,
    delivery: "10–14 days",
    emoji: "🎧",
  },
  {
    id: "MP-1010",
    name: "Full-Body Harness & Shock Lanyard Kit",
    category: "Fall Protection Equipment",
    supplier: "Height Safe Nigeria",
    description: "Five-point harness with dorsal and sternal D-rings, twin-leg energy-absorbing lanyard.",
    certifications: ["EN 361", "EN 355", "ANSI Z359.11"],
    price: 96500,
    unit: "per kit",
    availability: "In stock",
    rating: 4.9,
    reviews: 112,
    delivery: "4–7 days",
    emoji: "🪢",
  },
  {
    id: "MP-1011",
    name: "4-Gas Portable Detector (H₂S, CO, O₂, LEL)",
    category: "Gas Detectors",
    supplier: "Atlantic Detection Systems",
    description: "Rugged IP67 diffusion detector with datalogging, man-down alarm and docking compatibility.",
    certifications: ["ATEX II 1G", "IECEx"],
    price: 415000,
    unit: "per unit",
    availability: "Low stock",
    rating: 4.8,
    reviews: 63,
    delivery: "7–10 days",
    emoji: "📟",
  },
  {
    id: "MP-1012",
    name: "9kg DCP Fire Extinguisher",
    category: "Fire Extinguishers",
    supplier: "Guardian Fire Systems",
    description: "Dry chemical powder extinguisher with wall bracket and pressure gauge, ABC rated.",
    certifications: ["EN 3-7", "SON MANCAP"],
    price: 39500,
    unit: "per unit",
    availability: "In stock",
    rating: 4.4,
    reviews: 88,
    delivery: "3–6 days",
    emoji: "🧯",
  },
  {
    id: "MP-1013",
    name: "Industrial First Aid Kit (50-Person)",
    category: "First Aid Kits",
    supplier: "MedPro Occupational Health",
    description: "Wall-mounted BS-compliant kit with burns module, eye wash pods and trauma dressings.",
    certifications: ["BS 8599-1"],
    price: 74200,
    unit: "per kit",
    availability: "In stock",
    rating: 4.5,
    reviews: 51,
    delivery: "3–5 days",
    emoji: "🩹",
  },
  {
    id: "MP-1014",
    name: "Hydrocarbon Spill Response Kit (240L)",
    category: "Spill Response Kits",
    supplier: "EcoContain Environmental",
    description: "Wheeled bin with oil-only absorbent pads, booms, socks, disposal bags and PPE.",
    certifications: ["ISO 14001 supplier"],
    price: 189000,
    unit: "per kit",
    availability: "In stock",
    rating: 4.6,
    reviews: 37,
    delivery: "5–9 days",
    emoji: "🛢️",
  },
  {
    id: "MP-1015",
    name: "Reflective Traffic Cone 750mm",
    category: "Traffic Cones",
    supplier: "Niger Delta Industrial Ltd",
    description: "UV-stable PVC cone with two reflective collars and weighted base for windy terminals.",
    certifications: ["EN 13422"],
    price: 8900,
    unit: "per unit",
    availability: "In stock",
    rating: 4.1,
    reviews: 44,
    delivery: "2–4 days",
    emoji: "🚧",
  },
  {
    id: "MP-1016",
    name: "Photoluminescent Safety Signage Pack",
    category: "Safety Signage",
    supplier: "Guardian Fire Systems",
    description: "40-piece rigid PVC sign pack: mandatory, prohibition, warning and emergency egress.",
    certifications: ["ISO 7010"],
    price: 62000,
    unit: "per pack",
    availability: "In stock",
    rating: 4.3,
    reviews: 26,
    delivery: "4–7 days",
    emoji: "🪧",
  },
  {
    id: "MP-1017",
    name: "Lockout/Tagout Station (Group Kit)",
    category: "Lockout/Tagout Devices",
    supplier: "Height Safe Nigeria",
    description: "Group LOTO board with hasps, valve lockouts, breaker lockouts, tags and padlocks.",
    certifications: ["OSHA 1910.147 aligned"],
    price: 145000,
    unit: "per station",
    availability: "Made to order",
    rating: 4.7,
    reviews: 19,
    delivery: "10–15 days",
    emoji: "🔒",
  },
  {
    id: "MP-1018",
    name: "Combination Emergency Shower & Eye Wash",
    category: "Emergency Showers",
    supplier: "MedPro Occupational Health",
    description: "Galvanised pedestal unit with stay-open valves, dust covers and freeze-protection option.",
    certifications: ["ANSI Z358.1"],
    price: 720000,
    unit: "per unit",
    availability: "Made to order",
    rating: 4.8,
    reviews: 14,
    delivery: "14–21 days",
    emoji: "🚿",
  },
  {
    id: "MP-1019",
    name: "Wall-Mounted Eye Wash Station",
    category: "Eye Wash Stations",
    supplier: "MedPro Occupational Health",
    description: "Twin-spray eye wash with 15-minute flow, thermostatic mixing valve compatible.",
    certifications: ["ANSI Z358.1"],
    price: 235000,
    unit: "per unit",
    availability: "In stock",
    rating: 4.5,
    reviews: 22,
    delivery: "7–12 days",
    emoji: "👁️",
  },
  {
    id: "MP-1020",
    name: "Offshore Industrial PPE Bundle",
    category: "Industrial PPE",
    supplier: "Sahara PPE Manufacturing",
    description: "Complete per-worker kit: FR coveralls, helmet, boots, gloves, goggles, hearing protection.",
    certifications: ["Multi-standard bundle"],
    price: 168000,
    unit: "per worker",
    availability: "In stock",
    rating: 4.6,
    reviews: 77,
    delivery: "5–8 days",
    emoji: "📦",
  },
  {
    id: "MP-1021",
    name: "Confined Space Entry Training (Accredited)",
    category: "HSE Training Services",
    supplier: "Atlas HSE Academy",
    description: "Two-day accredited course with practical rescue drills, delivered on site for up to 12.",
    certifications: ["IOSH approved", "NEBOSH aligned"],
    price: 1850000,
    unit: "per cohort",
    availability: "Made to order",
    rating: 4.9,
    reviews: 33,
    delivery: "Schedule in 3 weeks",
    emoji: "🎓",
  },
  {
    id: "MP-1022",
    name: "Permit-to-Work Authorised Person Training",
    category: "HSE Training Services",
    supplier: "Atlas HSE Academy",
    description: "One-day competency course for PTW issuers and authorised persons with assessment.",
    certifications: ["IOSH approved"],
    price: 950000,
    unit: "per cohort",
    availability: "In stock",
    rating: 4.7,
    reviews: 21,
    delivery: "Schedule in 2 weeks",
    emoji: "📋",
  },
];

export type Supplier = {
  name: string;
  country: string;
  categories: string;
  rating: number;
  onTime: number;
  products: number;
  verified: boolean;
  since: string;
};

export const SUPPLIERS: Supplier[] = [
  { name: "Delta Safety Supplies Ltd", country: "Port Harcourt, NG", categories: "Head, eye & hi-vis PPE", rating: 4.6, onTime: 96, products: 128, verified: true, since: "2019" },
  { name: "Sahara PPE Manufacturing", country: "Lagos, NG", categories: "FR clothing, gloves, bundles", rating: 4.8, onTime: 92, products: 84, verified: true, since: "2016" },
  { name: "Atlantic Detection Systems", country: "Aberdeen, UK", categories: "Gas detection & hearing", rating: 4.8, onTime: 89, products: 46, verified: true, since: "2014" },
  { name: "Height Safe Nigeria", country: "Warri, NG", categories: "Fall protection & LOTO", rating: 4.7, onTime: 94, products: 61, verified: true, since: "2020" },
  { name: "Guardian Fire Systems", country: "Abuja, NG", categories: "Fire & signage", rating: 4.4, onTime: 88, products: 73, verified: true, since: "2018" },
  { name: "MedPro Occupational Health", country: "Lagos, NG", categories: "First aid & emergency wash", rating: 4.5, onTime: 91, products: 39, verified: true, since: "2017" },
  { name: "EcoContain Environmental", country: "Port Harcourt, NG", categories: "Spill & environment", rating: 4.6, onTime: 90, products: 28, verified: true, since: "2021" },
  { name: "Atlas HSE Academy", country: "Lagos, NG", categories: "Training & competency", rating: 4.9, onTime: 98, products: 22, verified: true, since: "2015" },
];

export type MarketOrder = {
  id: string;
  product: string;
  supplier: string;
  qty: number;
  value: number;
  status: "Quote requested" | "Quoted" | "Approved" | "In transit" | "Delivered";
  placed: string;
  eta: string;
};

export const ORDERS: MarketOrder[] = [
  { id: "PO-2026-0148", product: "Flame-Resistant Coveralls (Arc-Rated)", supplier: "Sahara PPE Manufacturing", qty: 120, value: 8160000, status: "In transit", placed: "2026-07-22", eta: "2026-08-05" },
  { id: "PO-2026-0147", product: "4-Gas Portable Detector", supplier: "Atlantic Detection Systems", qty: 12, value: 4980000, status: "Approved", placed: "2026-07-19", eta: "2026-08-09" },
  { id: "PO-2026-0146", product: "Full-Body Harness & Shock Lanyard Kit", supplier: "Height Safe Nigeria", qty: 40, value: 3860000, status: "Delivered", placed: "2026-07-02", eta: "2026-07-14" },
  { id: "RFQ-2026-0092", product: "Hydrocarbon Spill Response Kit (240L)", supplier: "EcoContain Environmental", qty: 6, value: 1134000, status: "Quoted", placed: "2026-07-28", eta: "Pending approval" },
  { id: "RFQ-2026-0093", product: "Confined Space Entry Training", supplier: "Atlas HSE Academy", qty: 2, value: 3700000, status: "Quote requested", placed: "2026-07-31", eta: "Awaiting supplier" },
];

export const QUOTE_REQUESTS = [
  { id: "RFQ-2026-0093", buyer: "Northgate Energy Plc", item: "Confined Space Entry Training × 2 cohorts", received: "2 hours ago", status: "New" },
  { id: "RFQ-2026-0091", buyer: "Meridian EPC Services", item: "Cut-Resistant Impact Gloves × 500", received: "1 day ago", status: "Responded" },
  { id: "RFQ-2026-0088", buyer: "Coastal Drilling Ltd", item: "9kg DCP Fire Extinguisher × 60", received: "3 days ago", status: "Won" },
];

export const naira = (v: number) => `₦${v.toLocaleString("en-NG")}`;
